### ISSUE TITLE
TBB Memory Leak in thread_state_container_test

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#1014]
The reason why `thread_state_container_test` fails randomly is because TBB is leaking memory:

http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-938/55/tests

```
==17181==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 12312 byte(s) in 3 object(s) allocated from:
    #0 0x5f2d82 in operator new[](unsigned long) (/jenkins/workspace/terrier_PR-938@3/build/debug/thread_state_container_test+0x5f2d82)
    #0 0x7fa386cde752 in tbb::interface7::internal::task_arena_base::internal_execute(tbb::interface7::internal::delegate_base&) const ??:?
SUMMARY: AddressSanitizer: 12312 byte(s) leaked in 3 allocation(s).
```

**Comment by apavlo** [comment]
Duplicate of #561
