### ISSUE TITLE
TPC-C Failing on Not Found Error

### ISSUE THREAD

**Issue by thepinetree** [cmu-db/terrier#1128]
Master currently fails on executing TPC-C with the following error format:
`    [java] 07:17:50,739 (Worker.java:506) ERROR - Fatal error when invoking Payment/02
     [java] java.lang.RuntimeException: D_ID=2 D_W_ID=15 not found!
     [java] 	at com.oltpbenchmark.benchmarks.tpcc.procedures.Payment.run(Payment.java:202)
     [java] 	at com.oltpbenchmark.benchmarks.tpcc.TPCCWorker.executeWork(TPCCWorker.java:74)
     [java] 	at com.oltpbenchmark.api.Worker.doWork(Worker.java:386)
     [java] 	at com.oltpbenchmark.api.Worker.run(Worker.java:296)
     [java] 	at java.base/java.lang.Thread.run(Thread.java:834)
BUILD FAILED
/home/ubuntu/oltpbench/build.xml:126: Java returned: 255`

Issue shows up in http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier-nightly/detail/support_server_cmd_test/22/pipeline (in raw output).

Related issue might be busy ramdisk. `sudo rm -rf /mnt/ramdisk` fails with “device or resource busy” but no open files exist when `lsof +D /mnt/ramdisk` is run.

**Comment by mbutrovich** [comment]
The district index it should be using for this lookup doesn't change, so I'm less inclined to believe it's related to either the UPDATE changes in TPL2 or the destination of the WAL. If I had to guess, it's something to do with the index lookup code.

**Comment by bialesdaniel** [comment]
Just to add some detail to the RAM disk part. I was running the Jenkins job that you added to link to when you mentioned this. The Jenkins job starts and kills the DB repeatedly so its possible that when you did the `rm -rf` the RAM disk was in use and then when you ran `lsof` it may have been between tests so it was not in use. Just a theory.

**Comment by thepinetree** [comment]
I thought so too, but I tried to do `rm -rf` again after `lsof` but still said it was busy. All the commands I used were run after I killed the DB.

**Comment by mbutrovich** [comment]
Have we tried to git bisect this to see when it broke? I'd try this commit:

https://github.com/cmu-db/noisepage/commit/d9d1c42cff40e687e9d62b84ac921f486b9a2c5d

which is when TPC-C got fixed after merging TPL2 and see if the bug is present. If it's not commence the bisecting.

**Comment by mbutrovich** [comment]
First time I think I've seen it on the Item table/index:

http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1224/89/pipeline

**Comment by mush-zhang** [comment]
Might get fixed in #1279 . This issue was introduced when we merge in TPL2, which is the first time we actually used `SetIndexedUpdate` in our codebase.
