### ISSUE TITLE
WHERE Clause Fails To Cast String to Timestamp Field

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#782]
If you try to SELECT using a timestamp field in the WHERE clause, the system dies a horrible death.

## To Reproduce

1. Create this table:
   ```
    CREATE TABLE order_line (
     ol_w_id int NOT NULL PRIMARY KEY,
     ol_d_id int NOT NULL PRIMARY KEY,
     ol_o_id int NOT NULL PRIMARY KEY,
     ol_number int NOT NULL PRIMARY KEY,
     ol_i_id int NOT NULL,
     ol_delivery_d timestamp,
     ol_amount decimal NOT NULL,
     ol_supply_w_id int NOT NULL,
     ol_quantity decimal NOT NULL,
     ol_dist_info char(24) NOT NULL
   ); 
   ```
2. Load one tuple:
   ```
   INSERT INTO ORDER_LINE VALUES (1, 1, 1 ,1, 21356, '2020-02-18 15:54:09.445000', 0.000000, 1, 5, 'eoredugusdupfqcyqtzkvta');
   ```

3. Try to SELECT it on `ol_delivery_d`:
   ```
   SELECT * FROM ORDER_LINE WHERE ol_delivery_d = '2020-02-18 15:54:09.445000';
   ```

## Server Error
```
[2020-02-18 11:01:40.148] [execution_logger] [error]  File (0x7fff58023338) <line:0:0> 
|- StructDecl (0x7fff5801d9f0) <line:0:0> State
| `- FieldDecl (0x7fff5801d980) <line:0:0> DUMMY
|   `- IdentifierExpr (0x7fff5801d950) <line:0:0>  'int32' int32
|- StructDecl (0x7fff5801d908) <line:0:0> Output4
| |- FieldDecl (0x7fff5801d3b8) <line:0:0> col0
| | `- IdentifierExpr (0x7fff5801d388) <line:0:0>  'Integer' Integer
| |- FieldDecl (0x7fff5801d430) <line:0:0> col1
| | `- IdentifierExpr (0x7fff5801d400) <line:0:0>  'Integer' Integer
| |- FieldDecl (0x7fff5801d4b0) <line:0:0> col2
| | `- IdentifierExpr (0x7fff5801d480) <line:0:0>  'Integer' Integer
| |- FieldDecl (0x7fff5801d540) <line:0:0> col3
| | `- IdentifierExpr (0x7fff5801d510) <line:0:0>  'Integer' Integer
| |- FieldDecl (0x7fff5801d5b0) <line:0:0> col4
| | `- IdentifierExpr (0x7fff5801d580) <line:0:0>  'Integer' Integer
| |- FieldDecl (0x7fff5801d660) <line:0:0> col5
| | `- IdentifierExpr (0x7fff5801d630) <line:0:0>  'Timestamp' Timestamp
| |- FieldDecl (0x7fff5801d6d0) <line:0:0> col6
| | `- IdentifierExpr (0x7fff5801d6a0) <line:0:0>  'Real' Real
| |- FieldDecl (0x7fff5801d740) <line:0:0> col7
| | `- IdentifierExpr (0x7fff5801d710) <line:0:0>  'Integer' Integer
| |- FieldDecl (0x7fff5801d7b0) <line:0:0> col8
| | `- IdentifierExpr (0x7fff5801d780) <line:0:0>  'Real' Real
| `- FieldDecl (0x7fff5801d8a0) <line:0:0> col9
|   `- IdentifierExpr (0x7fff5801d870) <line:0:0>  'StringVal' StringVal
|- FunctionDecl (0x7fff5801dc38) <line:0:0> setupFn
| `- FunctionLitExpr (0x7fff5801dc08) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' 
|   `- BlockStmt (0x7fff5801db78) <line:0:0> 
|     `- ReturnStmt (0x7fff58023758) <line:0:0> 
|- FunctionDecl (0x7fff5801de90) <line:0:0> teardownFn
| `- FunctionLitExpr (0x7fff5801de60) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' 
|   `- BlockStmt (0x7fff5801ddd0) <line:0:0> 
|     `- ReturnStmt (0x7fff580237b0) <line:0:0> 
|- FunctionDecl (0x7fff58020bc0) <line:0:0> pipeline0
| `- FunctionLitExpr (0x7fff58020b90) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' 
|   `- BlockStmt (0x7fff5801e028) <line:0:0> 
|     |- VariableDecl (0x7fff5801e100) <line:0:0> col_oids1 '[10]uint32'
|     |- AssignmentStmt (0x7fff5801e218) <line:0:0> 
|     | |- IndexExpr (0x7fff5801e1b8) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801e188) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801e158) <line:0:0>  'int64' 0
|     | `- ImplicitCastExpr (0x7fff58023830) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801e1e8) <line:0:0>  'int64' 10
|     |- AssignmentStmt (0x7fff5801e310) <line:0:0> 
|     | |- IndexExpr (0x7fff5801e2b0) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801e280) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801e250) <line:0:0>  'int64' 1
|     | `- ImplicitCastExpr (0x7fff58023860) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801e2e0) <line:0:0>  'int64' 9
|     |- AssignmentStmt (0x7fff5801e418) <line:0:0> 
|     | |- IndexExpr (0x7fff5801e3b8) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801e388) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801e358) <line:0:0>  'int64' 2
|     | `- ImplicitCastExpr (0x7fff58023890) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801e3e8) <line:0:0>  'int64' 8
|     |- AssignmentStmt (0x7fff5801e500) <line:0:0> 
|     | |- IndexExpr (0x7fff5801e4a0) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801e470) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801e440) <line:0:0>  'int64' 3
|     | `- ImplicitCastExpr (0x7fff580238c0) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801e4d0) <line:0:0>  'int64' 7
|     |- AssignmentStmt (0x7fff5801e628) <line:0:0> 
|     | |- IndexExpr (0x7fff5801e5c8) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801e598) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801e568) <line:0:0>  'int64' 4
|     | `- ImplicitCastExpr (0x7fff580238f0) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801e5f8) <line:0:0>  'int64' 2
|     |- AssignmentStmt (0x7fff5801e710) <line:0:0> 
|     | |- IndexExpr (0x7fff5801e6b0) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801e680) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801e650) <line:0:0>  'int64' 5
|     | `- ImplicitCastExpr (0x7fff58023920) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801e6e0) <line:0:0>  'int64' 1
|     |- AssignmentStmt (0x7fff5801e7f8) <line:0:0> 
|     | |- IndexExpr (0x7fff5801e798) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801e768) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801e738) <line:0:0>  'int64' 6
|     | `- ImplicitCastExpr (0x7fff58023950) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801e7c8) <line:0:0>  'int64' 3
|     |- AssignmentStmt (0x7fff5801e8e0) <line:0:0> 
|     | |- IndexExpr (0x7fff5801e880) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801e850) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801e820) <line:0:0>  'int64' 7
|     | `- ImplicitCastExpr (0x7fff58023980) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801e8b0) <line:0:0>  'int64' 4
|     |- AssignmentStmt (0x7fff5801ea48) <line:0:0> 
|     | |- IndexExpr (0x7fff5801e9e8) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801e9b8) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801e988) <line:0:0>  'int64' 8
|     | `- ImplicitCastExpr (0x7fff580239b0) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801ea18) <line:0:0>  'int64' 5
|     |- AssignmentStmt (0x7fff5801eb30) <line:0:0> 
|     | |- IndexExpr (0x7fff5801ead0) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x7fff5801eaa0) <line:0:0>  '[10]uint32' col_oids1
|     | | `- LitExpr (0x7fff5801ea70) <line:0:0>  'int64' 9
|     | `- ImplicitCastExpr (0x7fff580239e0) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x7fff5801eb00) <line:0:0>  'int64' 6
|     |- VariableDecl (0x7fff5801eb88) <line:0:0> tvi0 'TableVectorIterator'
|     |- CallExpr (0x7fff5801ed18) <line:0:0>  'nil' <Builtin> 
|     | |- IdentifierExpr (0x7fff5801ebd8) <line:0:0> tableIterInit
|     | |- UnaryOpExpr (0x7fff5801ec38) <line:0:0>  '*TableVectorIterator' '&'
|     | | `- IdentifierExpr (0x7fff5801ec08) <line:0:0>  'TableVectorIterator' tvi0
|     | |- IdentifierExpr (0x7fff5801ec68) <line:0:0>  '*ExecutionContext' execCtx
|     | |- LitExpr (0x7fff5801ec98) <line:0:0>  'int64' 1002
|     | `- IdentifierExpr (0x7fff5801ecc8) <line:0:0>  '[10]uint32' col_oids1
|     |- ForStmt (0x7fff5801eeb8) <line:0:0> 
|     | |- CallExpr (0x7fff5801ee20) <line:0:0>  'bool' <Builtin> 
|     | | |- IdentifierExpr (0x7fff5801ede8) <line:0:0> tableIterAdvance
|     | | `- UnaryOpExpr (0x7fff5801edb8) <line:0:0>  '*TableVectorIterator' '&'
|     | |   `- IdentifierExpr (0x7fff5801ed88) <line:0:0>  'TableVectorIterator' tvi0
|     | `- BlockStmt (0x7fff5801ee70) <line:0:0> 
|     |   |- VariableDecl (0x7fff5801efd8) <line:0:0> pci2
|     |   | `- CallExpr (0x7fff5801ef88) <line:0:0>  '*ProjectedColumnsIterator' <Builtin> 
|     |   |   |- IdentifierExpr (0x7fff5801ef50) <line:0:0> tableIterGetPCI
|     |   |   `- UnaryOpExpr (0x7fff5801ef20) <line:0:0>  '*TableVectorIterator' '&'
|     |   |     `- IdentifierExpr (0x7fff5801eef0) <line:0:0>  'TableVectorIterator' tvi0
|     |   `- ForStmt (0x7fff5801f208) <line:0:0> 
|     |     |- CallExpr (0x7fff5801f098) <line:0:0>  'bool' <Builtin> 
|     |     | |- IdentifierExpr (0x7fff5801f060) <line:0:0> pciHasNext
|     |     | `- IdentifierExpr (0x7fff5801f030) <line:0:0>  '*ProjectedColumnsIterator' pci2
|     |     |- CallExpr (0x7fff5801f150) <line:0:0>  'bool' <Builtin> 
|     |     | |- IdentifierExpr (0x7fff5801f118) <line:0:0> pciAdvance
|     |     | `- IdentifierExpr (0x7fff5801f0e8) <line:0:0>  '*ProjectedColumnsIterator' pci2
|     |     `- BlockStmt (0x7fff5801f1c0) <line:0:0> 
|     |       `- IfStmt (0x7fff5801f4a8) <line:0:0> 
|     |         |- ComparisonOpExpr (0x7fff5801f428) <line:0:0> '=='
|     |         | |- CallExpr (0x7fff5801f2f0) <line:0:0>  'Timestamp' <Builtin> 
|     |         | | |- IdentifierExpr (0x7fff5801f250) <line:0:0> pciGetTimestampNull
|     |         | | |- IdentifierExpr (0x7fff5801f280) <line:0:0>  '*ProjectedColumnsIterator' pci2
|     |         | | `- LitExpr (0x7fff5801f2b0) <line:0:0>  'int64' 1
|     |         | `- CallExpr (0x7fff5801f3d8) <line:0:0>  'StringVal' <Builtin> 
|     |         |   |- IdentifierExpr (0x7fff5801f3a0) <line:0:0> stringToSql
|     |         |   `- LitExpr (0x7fff5801f370) <line:0:0>  'string' 2020-02-18 15:54:09.445000
|     |         `- BlockStmt (0x7fff5801f460) <line:0:0> 
|     |           |- VariableDecl (0x7fff5801f598) <line:0:0> slot3
|     |           | `- CallExpr (0x7fff5801f548) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff5801f510) <line:0:0> pciGetSlot
|     |           |   `- IdentifierExpr (0x7fff5801f4e0) <line:0:0> pci2
|     |           |- VariableDecl (0x7fff5801f798) <line:0:0> out5
|     |           | `- CallExpr (0x7fff5801f748) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff5801f6d8) <line:0:0> ptrCast
|     |           |   |- UnaryOpExpr (0x7fff5801f708) <line:0:0> '*'
|     |           |   | `- IdentifierExpr (0x7fff5801f6a8) <line:0:0> Output4
|     |           |   `- CallExpr (0x7fff5801f658) <line:0:0> <Builtin> 
|     |           |     |- IdentifierExpr (0x7fff5801f620) <line:0:0> outputAlloc
|     |           |     `- IdentifierExpr (0x7fff5801f5f0) <line:0:0> execCtx
|     |           |- AssignmentStmt (0x7fff5801f978) <line:0:0> 
|     |           | |- MemberExpr (0x7fff5801f858) <line:0:0> 
|     |           | | |- IdentifierExpr (0x7fff5801f7f8) <line:0:0> out5
|     |           | | `- IdentifierExpr (0x7fff5801f828) <line:0:0> col0
|     |           | `- CallExpr (0x7fff5801f928) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff5801f888) <line:0:0> pciGetInt
|     |           |   |- IdentifierExpr (0x7fff5801f8b8) <line:0:0> pci2
|     |           |   `- LitExpr (0x7fff5801f8e8) <line:0:0> 4
|     |           |- AssignmentStmt (0x7fff5801fb40) <line:0:0> 
|     |           | |- MemberExpr (0x7fff5801fa20) <line:0:0> 
|     |           | | |- IdentifierExpr (0x7fff5801f9c0) <line:0:0> out5
|     |           | | `- IdentifierExpr (0x7fff5801f9f0) <line:0:0> col1
|     |           | `- CallExpr (0x7fff5801faf0) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff5801fa50) <line:0:0> pciGetInt
|     |           |   |- IdentifierExpr (0x7fff5801fa80) <line:0:0> pci2
|     |           |   `- LitExpr (0x7fff5801fab0) <line:0:0> 5
|     |           |- AssignmentStmt (0x7fff5801fce8) <line:0:0> 
|     |           | |- MemberExpr (0x7fff5801fbc8) <line:0:0> 
|     |           | | |- IdentifierExpr (0x7fff5801fb68) <line:0:0> out5
|     |           | | `- IdentifierExpr (0x7fff5801fb98) <line:0:0> col2
|     |           | `- CallExpr (0x7fff5801fc98) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff5801fbf8) <line:0:0> pciGetInt
|     |           |   |- IdentifierExpr (0x7fff5801fc28) <line:0:0> pci2
|     |           |   `- LitExpr (0x7fff5801fc58) <line:0:0> 6
|     |           |- AssignmentStmt (0x7fff5801fed0) <line:0:0> 
|     |           | |- MemberExpr (0x7fff5801fdb0) <line:0:0> 
|     |           | | |- IdentifierExpr (0x7fff5801fd50) <line:0:0> out5
|     |           | | `- IdentifierExpr (0x7fff5801fd80) <line:0:0> col3
|     |           | `- CallExpr (0x7fff5801fe80) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff5801fde0) <line:0:0> pciGetInt
|     |           |   |- IdentifierExpr (0x7fff5801fe10) <line:0:0> pci2
|     |           |   `- LitExpr (0x7fff5801fe40) <line:0:0> 7
|     |           |- AssignmentStmt (0x7fff58020078) <line:0:0> 
|     |           | |- MemberExpr (0x7fff5801ff58) <line:0:0> 
|     |           | | |- IdentifierExpr (0x7fff5801fef8) <line:0:0> out5
|     |           | | `- IdentifierExpr (0x7fff5801ff28) <line:0:0> col4
|     |           | `- CallExpr (0x7fff58020028) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff5801ff88) <line:0:0> pciGetInt
|     |           |   |- IdentifierExpr (0x7fff5801ffb8) <line:0:0> pci2
|     |           |   `- LitExpr (0x7fff5801ffe8) <line:0:0> 8
|     |           |- AssignmentStmt (0x7fff58020220) <line:0:0> 
|     |           | |- MemberExpr (0x7fff58020100) <line:0:0> 
|     |           | | |- IdentifierExpr (0x7fff580200a0) <line:0:0> out5
|     |           | | `- IdentifierExpr (0x7fff580200d0) <line:0:0> col5
|     |           | `- CallExpr (0x7fff580201d0) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff58020130) <line:0:0> pciGetTimestampNull
|     |           |   |- IdentifierExpr (0x7fff58020160) <line:0:0> pci2
|     |           |   `- LitExpr (0x7fff58020190) <line:0:0> 1
|     |           |- AssignmentStmt (0x7fff580203c8) <line:0:0> 
|     |           | |- MemberExpr (0x7fff580202a8) <line:0:0> 
|     |           | | |- IdentifierExpr (0x7fff58020248) <line:0:0> out5
|     |           | | `- IdentifierExpr (0x7fff58020278) <line:0:0> col6
|     |           | `- CallExpr (0x7fff58020378) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff580202d8) <line:0:0> pciGetDouble
|     |           |   |- IdentifierExpr (0x7fff58020308) <line:0:0> pci2
|     |           |   `- LitExpr (0x7fff58020338) <line:0:0> 2
|     |           |- AssignmentStmt (0x7fff580205f0) <line:0:0> 
|     |           | |- MemberExpr (0x7fff580204d0) <line:0:0> 
|     |           | | |- IdentifierExpr (0x7fff58020470) <line:0:0> out5
|     |           | | `- IdentifierExpr (0x7fff580204a0) <line:0:0> col7
|     |           | `- CallExpr (0x7fff580205a0) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff58020500) <line:0:0> pciGetInt
|     |           |   |- IdentifierExpr (0x7fff58020530) <line:0:0> pci2
|     |           |   `- LitExpr (0x7fff58020560) <line:0:0> 9
|     |           |- AssignmentStmt (0x7fff58020798) <line:0:0> 
|     |           | |- MemberExpr (0x7fff58020678) <line:0:0> 
|     |           | | |- IdentifierExpr (0x7fff58020618) <line:0:0> out5
|     |           | | `- IdentifierExpr (0x7fff58020648) <line:0:0> col8
|     |           | `- CallExpr (0x7fff58020748) <line:0:0> <Builtin> 
|     |           |   |- IdentifierExpr (0x7fff580206a8) <line:0:0> pciGetDouble
|     |           |   |- IdentifierExpr (0x7fff580206d8) <line:0:0> pci2
|     |           |   `- LitExpr (0x7fff58020708) <line:0:0> 3
|     |           `- AssignmentStmt (0x7fff58020940) <line:0:0> 
|     |             |- MemberExpr (0x7fff58020820) <line:0:0> 
|     |             | |- IdentifierExpr (0x7fff580207c0) <line:0:0> out5
|     |             | `- IdentifierExpr (0x7fff580207f0) <line:0:0> col9
|     |             `- CallExpr (0x7fff580208f0) <line:0:0> <Builtin> 
|     |               |- IdentifierExpr (0x7fff58020850) <line:0:0> pciGetVarlen
|     |               |- IdentifierExpr (0x7fff58020880) <line:0:0> pci2
|     |               `- LitExpr (0x7fff580208b0) <line:0:0> 0
|     |- CallExpr (0x7fff58020a00) <line:0:0>  'nil' <Builtin> 
|     | |- IdentifierExpr (0x7fff580209c8) <line:0:0> tableIterClose
|     | `- UnaryOpExpr (0x7fff58020998) <line:0:0>  '*TableVectorIterator' '&'
|     |   `- IdentifierExpr (0x7fff58020968) <line:0:0>  'TableVectorIterator' tvi0
|     |- CallExpr (0x7fff58020ad8) <line:0:0>  'nil' <Builtin> 
|     | |- IdentifierExpr (0x7fff58020aa0) <line:0:0> outputFinalize
|     | `- IdentifierExpr (0x7fff58020a70) <line:0:0>  '*ExecutionContext' execCtx
|     `- ReturnStmt (0x7fff58023ad0) <line:0:0> 
`- FunctionDecl (0x7fff58023308) <line:0:0> main
  `- FunctionLitExpr (0x7fff580232d8) <line:0:0>  '(*ExecutionContext)->int32' 
    `- BlockStmt (0x7fff58022d40) <line:0:0> 
      |- VariableDecl (0x7fff58022db8) <line:0:0> state 'struct{int32}'
      |- CallExpr (0x7fff58022ee0) <line:0:0>  'nil' <Regular> 
      | |- IdentifierExpr (0x7fff58022e10) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' setupFn
      | |- UnaryOpExpr (0x7fff58022e70) <line:0:0>  '*struct{int32}' '&'
      | | `- IdentifierExpr (0x7fff58022e40) <line:0:0>  'struct{int32}' state
      | `- IdentifierExpr (0x7fff58022ea0) <line:0:0>  '*ExecutionContext' execCtx
      |- CallExpr (0x7fff58023030) <line:0:0>  'nil' <Regular> 
      | |- IdentifierExpr (0x7fff58022f60) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' pipeline0
      | |- UnaryOpExpr (0x7fff58022fc0) <line:0:0>  '*struct{int32}' '&'
      | | `- IdentifierExpr (0x7fff58022f90) <line:0:0>  'struct{int32}' state
      | `- IdentifierExpr (0x7fff58022ff0) <line:0:0>  '*ExecutionContext' execCtx
      |- CallExpr (0x7fff58023190) <line:0:0>  'nil' <Regular> 
      | |- IdentifierExpr (0x7fff580230c0) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' teardownFn
      | |- UnaryOpExpr (0x7fff58023120) <line:0:0>  '*struct{int32}' '&'
      | | `- IdentifierExpr (0x7fff580230f0) <line:0:0>  'struct{int32}' state
      | `- IdentifierExpr (0x7fff58023150) <line:0:0>  '*ExecutionContext' execCtx
      `- ReturnStmt (0x7fff58023230) <line:0:0> 
        `- ImplicitCastExpr (0x7fff58023c40) <line:0:0>  'int32' <IntegralCast>
          `- LitExpr (0x7fff58023200) <line:0:0>  'int64' 0

[2020-02-18 11:01:40.149] [execution_logger] [error] Type-checking error! 
 Line: 0, Col: 0 => binary operation '==' does not support types 'Timestamp' and 'StringVal'

[2020-02-18 11:01:40.149] [execution_logger] [error] Dumping AST:

Thread 8 "terrier" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffed9f5700 (LWP 7922)]
terrier::execution::ExecutableQuery::Run (this=this@entry=0x7fffed9f4740, exec_ctx=exec_ctx@entry=..., mode=mode@entry=<incomplete type>)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/executable_query.cpp:38
38        if (!tpl_module_->GetFunction("main", mode, &main)) {
```

**Backtrace**
```
#0  terrier::execution::ExecutableQuery::Run (this=this@entry=0x7fffed9f4740, exec_ctx=exec_ctx@entry=..., mode=mode@entry=<incomplete type>)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/executable_query.cpp:38
#1  0x0000555555a4518f in terrier::trafficcop::TrafficCop::CodegenAndRunPhysicalPlan (this=this@entry=0x55555771ed10, connection_ctx=..., connection_ctx@entry=..., out=out@entry=..., physical_plan=..., 
    query_type=query_type@entry=terrier::network::QueryType::QUERY_SELECT) at /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop.cpp:338
#2  0x0000555555a46ec6 in terrier::trafficcop::TrafficCop::ExecuteStatement (this=this@entry=0x55555771ed10, connection_ctx=connection_ctx@entry=..., out=out@entry=..., parse_result=..., query_type=<optimized out>)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop.cpp:302
#3  0x000055555599a618 in terrier::network::SimpleQueryCommand::Exec (this=<optimized out>, interpreter=..., out=..., t_cop=..., connection=...)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_network_commands.cpp:68
#4  0x000055555599d2b5 in terrier::network::PostgresProtocolInterpreter::Process (this=0x555557702260, in=..., out=..., t_cop=..., context=...)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_protocol_interpreter.cpp:38
#5  0x0000555555b9131e in terrier::network::ConnectionHandle::StateMachine::Accept (this=this@entry=0x7fff58000c90, action=<optimized out>, connection=..., connection@entry=...)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:155
#6  0x0000555555b917e6 in terrier::network::ConnectionHandle::HandleEvent (flags=<optimized out>, fd=<optimized out>, this=0x7fff58000c70)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:97
#7  terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const (arg=0x7fff58000c70, flags=<optimized out>, fd=<optimized out>, __closure=0x0)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
#8  terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) () at /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
#9  0x00007ffff79838f8 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#10 0x00007ffff798433f in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#11 0x0000555555a97eab in terrier::EventUtil::EventBaseDispatch (base=<optimized out>) at /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/event_util.h:92
#12 terrier::common::NotifiableTask::EventLoop (this=<optimized out>) at /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:159
#13 terrier::common::NotifiableTask::RunTask (this=<optimized out>) at /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:166
#14 terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}::operator()() const (
    __closure=0x7fff64001aa8) at /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/dedicated_thread_registry.h:82
#15 std::__invoke_impl<void, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(std::__invoke_other, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) (__f=...)
    at /usr/include/c++/7/bits/invoke.h:60
#16 std::__invoke<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#17 std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x7fff64001aa8) at /usr/include/c++/7/thread:234
#18 std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::operator()() (this=0x7fff64001aa8) at /usr/include/c++/7/thread:243
#19 std::thread::_State_impl<std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> > >::_M_run() (this=0x7fff64001aa0) at /usr/include/c++/7/thread:186
#20 0x00007ffff6c0f66f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#21 0x00007ffff7bbd6db in start_thread (arg=0x7fffed9f5700) at pthread_create.c:463
#22 0x00007ffff62cc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by lmwnshn** [comment]
#762 fixes this.
