### ISSUE TITLE
Double-Free ASAN Error On Network Connection Close

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#789]
I ran `NetworkTests::RacerTest` in an infinite loop until it trips an error. This is a new error that showed up today that I hadn't seen before

**Client**
```
$ cmake -DCMAKE_BUILD_TYPE=relwithdebinfo -DTERRIER_BUILD_BENCHMARKS=OFF -DTERRIER_USE_ASAN=yes ..
$ make network_test
$ cnt=0 ; while [ true ]; do echo $cnt ; time ./relwithdebinfo/network_test ; test $? -ne 0 && break; cnt=$((cnt + 1)) ; done ; echo $cnt
```

**Server**
```
[==========] Running 1 test from 1 test case.                                                       
[----------] Global test environment set-up.                                                                                                                                                                                   
[----------] 1 test from NetworkTests                                                                                                                                                                                          
[ RUN      ] NetworkTests.RacerTest
[2020-02-21 09:55:57.175] [network_logger] [info] Listening on port 15721
=================================================================
==25323==ERROR: AddressSanitizer: attempting double-free on 0x60c00001c240 in thread T7:
    #0 0x7fbf610fb7b8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8)
    #1 0x5649fef358b6 in terrier::common::NotifiableTask::UnregisterEvent(event*) /home/pavlo/Documents/Peloton/Github/terrier/src/common/notifiable_task.cpp:43
    #2 0x5649ff07227e in terrier::network::ConnectionHandle::TryCloseConnection() /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:182
    #3 0x5649ff0723e7 in operator() /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:112
    #4 0x5649ff0723e7 in _FUN /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:112
    #5 0x5649ff0725d8 in terrier::network::ConnectionHandle::StateMachine::Accept(terrier::network::Transition, terrier::common::ManagedPointer<terrier::network::ConnectionHandle>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:155
    #6 0x5649ff073754 in terrier::network::ConnectionHandle::HandleEvent(int, short) /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:97
    #7 0x5649ff073754 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
    #8 0x5649ff073754 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
    #9 0x7fbf60dea8f7  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1e8f7)
    #10 0x7fbf60deb33e in event_base_loop (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1f33e)
    #11 0x5649febe7d86 in terrier::EventUtil::EventBaseDispatch(event_base*) /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/event_util.h:92
    #12 0x5649febe7d86 in terrier::common::NotifiableTask::EventLoop() /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:159
    #13 0x5649febe7d86 in terrier::common::NotifiableTask::RunTask() /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:166
    #14 0x5649febe7d86 in terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}::operator()() const /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/dedicated_thread_registry.h:82
    #15 0x5649febe7d86 in void std::__invoke_impl<void, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambd a()#1}>(std::__invoke_other, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) /usr/include/c++/ 7/bits/invoke.h:60
    #16 0x5649febe7d86 in std::__invoke_result<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>:: type std::__invoke<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::Ma nagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) /usr/include/c++/7/bits/invoke.h:95
    #17 0x5649febe7d86 in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::Register DedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier ::network::ConnectionHandleFactory>)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/7/thread:234
    #18 0x5649febe7d86 in std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::Connect ionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{la mbda()#1}> >::operator()() /usr/include/c++/7/thread:243
    #19 0x5649febe7d86 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread< terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::Conne ctionHandleFactory>)::{lambda()#1}> > >::_M_run() /usr/include/c++/7/thread:186
    #20 0x7fbf5fe5766e  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd66e)
    #21 0x7fbf6012a6da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #22 0x7fbf5f51488e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12188e)

0x60c00001c240 is located 0 bytes inside of 128-byte region [0x60c00001c240,0x60c00001c2c0)
freed by thread T8 here:
    #0 0x7fbf610fb7b8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8)
    #1 0x5649fef358b6 in terrier::common::NotifiableTask::UnregisterEvent(event*) /home/pavlo/Documents/Peloton/Github/terrier/src/common/notifiable_task.cpp:43

previously allocated by thread T8 here:
    #0 0x7fbf610fbb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7fbf60deb895 in event_new (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1f895)

Thread T7 created by T3 here:
    #0 0x7fbf61054d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7fbf5fe57924 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd924)

Thread T3 created by T0 here:
    #0 0x7fbf61054d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7fbf5fe57924 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd924)
    #2 0x5649fe5ec328 in terrier::network::NetworkTests::SetUp() /home/pavlo/Documents/Peloton/Github/terrier/test/network/network_test.cpp:80

Thread T8 created by T3 here:
    #0 0x7fbf61054d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7fbf5fe57924 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd924)

SUMMARY: AddressSanitizer: double-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8) in __interceptor_free
==25323==ABORTING
```

**Comment by apavlo** [comment]
Closing this because I don't think we've seen this problem for several months.
