### ISSUE TITLE
Concat Operator (||) Does Not Work

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#804]
We are not able to use the concat operator `||` in queries.

## Client
```
terrier=# CREATE TABLE xxx (id INT);
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1),(2),(3);
INSERT 0 3
terrier=# SELECT 'A' || 'P' FROM xxx;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

## Server
```
[2020-03-03 13:09:04.528] [execution_logger] [error] Type-checking error! 
 Line: 0, Col: 0 => cannot assign type 'Integer' to type 'StringVal'

[2020-03-03 13:09:04.528] [execution_logger] [error] Dumping AST:
[2020-03-03 13:09:04.530] [execution_logger] [error]  File (0x62900006bbb0) <line:0:0> 
|- StructDecl (0x629000069ad8) <line:0:0> State
| `- FieldDecl (0x629000069a68) <line:0:0> DUMMY
|   `- IdentifierExpr (0x629000069a38) <line:0:0>  'int32' int32
|- StructDecl (0x6290000699f0) <line:0:0> Output4
| `- FieldDecl (0x629000069980) <line:0:0> col0
|   `- IdentifierExpr (0x629000069950) <line:0:0>  'StringVal' StringVal
|- FunctionDecl (0x629000069d20) <line:0:0> setupFn
| `- FunctionLitExpr (0x629000069cf0) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' 
|   `- BlockStmt (0x629000069c60) <line:0:0> 
|     `- ReturnStmt (0x62900006bd78) <line:0:0> 
|- FunctionDecl (0x629000069f78) <line:0:0> teardownFn
| `- FunctionLitExpr (0x629000069f48) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' 
|   `- BlockStmt (0x629000069eb8) <line:0:0> 
|     `- ReturnStmt (0x62900006bdd0) <line:0:0> 
|- FunctionDecl (0x62900006b490) <line:0:0> pipeline0
| `- FunctionLitExpr (0x62900006b460) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' 
|   `- BlockStmt (0x62900006a110) <line:0:0> 
|     |- CallExpr (0x62900006a200) <line:0:0>  'nil' <Builtin> 
|     | |- IdentifierExpr (0x62900006a1b8) <line:0:0> execCtxStartResourceTracker
|     | |- IdentifierExpr (0x62900006a158) <line:0:0>  '*ExecutionContext' execCtx
|     | `- LitExpr (0x62900006a188) <line:0:0>  'int64' 4
|     |- VariableDecl (0x62900006a308) <line:0:0> col_oids1 '[1]uint32'
|     |- AssignmentStmt (0x62900006a428) <line:0:0> 
|     | |- IndexExpr (0x62900006a3c8) <line:0:0>  'uint32' 
|     | | |- IdentifierExpr (0x62900006a398) <line:0:0>  '[1]uint32' col_oids1
|     | | `- LitExpr (0x62900006a368) <line:0:0>  'int64' 0
|     | `- ImplicitCastExpr (0x62900006be50) <line:0:0>  'uint32' <IntegralCast>
|     |   `- LitExpr (0x62900006a3f8) <line:0:0>  'int64' 1
|     |- VariableDecl (0x62900006a4a0) <line:0:0> tvi0 'TableVectorIterator'
|     |- CallExpr (0x62900006a630) <line:0:0>  'nil' <Builtin> 
|     | |- IdentifierExpr (0x62900006a4f0) <line:0:0> tableIterInit
|     | |- UnaryOpExpr (0x62900006a550) <line:0:0>  '*TableVectorIterator' '&'
|     | | `- IdentifierExpr (0x62900006a520) <line:0:0>  'TableVectorIterator' tvi0
|     | |- IdentifierExpr (0x62900006a580) <line:0:0>  '*ExecutionContext' execCtx
|     | |- LitExpr (0x62900006a5b0) <line:0:0>  'int64' 1002
|     | `- IdentifierExpr (0x62900006a5e0) <line:0:0>  '[1]uint32' col_oids1
|     |- ForStmt (0x62900006a810) <line:0:0> 
|     | |- CallExpr (0x62900006a778) <line:0:0>  'bool' <Builtin> 
|     | | |- IdentifierExpr (0x62900006a740) <line:0:0> tableIterAdvance
|     | | `- UnaryOpExpr (0x62900006a710) <line:0:0>  '*TableVectorIterator' '&'
|     | |   `- IdentifierExpr (0x62900006a6e0) <line:0:0>  'TableVectorIterator' tvi0
|     | `- BlockStmt (0x62900006a7c8) <line:0:0> 
|     |   |- VariableDecl (0x62900006a930) <line:0:0> pci2
|     |   | `- CallExpr (0x62900006a8e0) <line:0:0>  '*ProjectedColumnsIterator' <Builtin> 
|     |   |   |- IdentifierExpr (0x62900006a8a8) <line:0:0> tableIterGetPCI
|     |   |   `- UnaryOpExpr (0x62900006a878) <line:0:0>  '*TableVectorIterator' '&'
|     |   |     `- IdentifierExpr (0x62900006a848) <line:0:0>  'TableVectorIterator' tvi0
|     |   `- ForStmt (0x62900006ab60) <line:0:0> 
|     |     |- CallExpr (0x62900006a9f0) <line:0:0>  'bool' <Builtin> 
|     |     | |- IdentifierExpr (0x62900006a9b8) <line:0:0> pciHasNext
|     |     | `- IdentifierExpr (0x62900006a988) <line:0:0>  '*ProjectedColumnsIterator' pci2
|     |     |- CallExpr (0x62900006aaa8) <line:0:0>  'bool' <Builtin> 
|     |     | |- IdentifierExpr (0x62900006aa70) <line:0:0> pciAdvance
|     |     | `- IdentifierExpr (0x62900006aa40) <line:0:0>  '*ProjectedColumnsIterator' pci2
|     |     `- BlockStmt (0x62900006ab18) <line:0:0> 
|     |       |- VariableDecl (0x62900006ac60) <line:0:0> slot3
|     |       | `- CallExpr (0x62900006ac10) <line:0:0>  'TupleSlot' <Builtin> 
|     |       |   |- IdentifierExpr (0x62900006abd8) <line:0:0> pciGetSlot
|     |       |   `- IdentifierExpr (0x62900006aba8) <line:0:0>  '*ProjectedColumnsIterator' pci2
|     |       |- VariableDecl (0x62900006ae60) <line:0:0> out5
|     |       | `- CallExpr (0x62900006ae10) <line:0:0>  '*struct{StringVal}' <Builtin> 
|     |       |   |- IdentifierExpr (0x62900006ada0) <line:0:0> ptrCast
|     |       |   |- PointerTypeRepr (0x62900006bec0) <line:0:0> 
|     |       |   | `- IdentifierExpr (0x62900006ad70) <line:0:0>  'struct{StringVal}' Output4
|     |       |   `- CallExpr (0x62900006ad20) <line:0:0>  '*uint8' <Builtin> 
|     |       |     |- IdentifierExpr (0x62900006ace8) <line:0:0> outputAlloc
|     |       |     `- IdentifierExpr (0x62900006acb8) <line:0:0>  '*ExecutionContext' execCtx
|     |       `- AssignmentStmt (0x62900006b008) <line:0:0> 
|     |         |- MemberExpr (0x62900006af20) <line:0:0>  'StringVal' 
|     |         | |- IdentifierExpr (0x62900006aec0) <line:0:0>  '*struct{StringVal}' out5
|     |         | `- IdentifierExpr (0x62900006aef0) <line:0:0> col0
|     |         `- CallExpr (0x62900006afb8) <line:0:0>  'Integer' <Builtin> 
|     |           |- IdentifierExpr (0x62900006af80) <line:0:0> intToSql
|     |           `- LitExpr (0x62900006af50) <line:0:0>  'int64' 0
|     |- CallExpr (0x62900006b0e8) <line:0:0>  'nil' <Builtin> 
|     | |- IdentifierExpr (0x62900006b0b0) <line:0:0> tableIterClose
|     | `- UnaryOpExpr (0x62900006b080) <line:0:0>  '*TableVectorIterator' '&'
|     |   `- IdentifierExpr (0x62900006b050) <line:0:0>  'TableVectorIterator' tvi0
|     |- CallExpr (0x62900006b1c0) <line:0:0>  'nil' <Builtin> 
|     | |- IdentifierExpr (0x62900006b188) <line:0:0> outputFinalize
|     | `- IdentifierExpr (0x62900006b158) <line:0:0>  '*ExecutionContext' execCtx
|     |- CallExpr (0x62900006b328) <line:0:0>  'nil' <Builtin> 
|     | |- IdentifierExpr (0x62900006b2c0) <line:0:0> execCtxEndPipelineTracker
|     | |- IdentifierExpr (0x62900006b230) <line:0:0>  '*ExecutionContext' execCtx
|     | |- LitExpr (0x62900006b260) <line:0:0>  'int64' 2
|     | `- LitExpr (0x62900006b290) <line:0:0>  'int64' 0
|     `- ReturnStmt (0x62900006bf90) <line:0:0> 
`- FunctionDecl (0x62900006bb80) <line:0:0> main
  `- FunctionLitExpr (0x62900006bb50) <line:0:0>  '(*ExecutionContext)->int32' 
    `- BlockStmt (0x62900006b5b8) <line:0:0> 
      |- VariableDecl (0x62900006b630) <line:0:0> state 'struct{int32}'
      |- CallExpr (0x62900006b758) <line:0:0>  'nil' <Regular> 
      | |- IdentifierExpr (0x62900006b688) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' setupFn
      | |- UnaryOpExpr (0x62900006b6e8) <line:0:0>  '*struct{int32}' '&'
      | | `- IdentifierExpr (0x62900006b6b8) <line:0:0>  'struct{int32}' state
      | `- IdentifierExpr (0x62900006b718) <line:0:0>  '*ExecutionContext' execCtx
      |- CallExpr (0x62900006b8a8) <line:0:0>  'nil' <Regular> 
      | |- IdentifierExpr (0x62900006b7d8) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' pipeline0
      | |- UnaryOpExpr (0x62900006b838) <line:0:0>  '*struct{int32}' '&'
      | | `- IdentifierExpr (0x62900006b808) <line:0:0>  'struct{int32}' state
      | `- IdentifierExpr (0x62900006b868) <line:0:0>  '*ExecutionContext' execCtx
      |- CallExpr (0x62900006ba08) <line:0:0>  'nil' <Regular> 
      | |- IdentifierExpr (0x62900006b938) <line:0:0>  '(*struct{int32},*ExecutionContext)->nil' teardownFn
      | |- UnaryOpExpr (0x62900006b998) <line:0:0>  '*struct{int32}' '&'
      | | `- IdentifierExpr (0x62900006b968) <line:0:0>  'struct{int32}' state
      | `- IdentifierExpr (0x62900006b9c8) <line:0:0>  '*ExecutionContext' execCtx
      `- ReturnStmt (0x62900006baa8) <line:0:0> 
        `- ImplicitCastExpr (0x62900006c000) <line:0:0>  'int32' <IntegralCast>
          `- LitExpr (0x62900006ba78) <line:0:0>  'int64' 0

AddressSanitizer:DEADLYSIGNAL
=================================================================
==11984==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55920f6803ea bp 0x0fe85cc5c50c sp 0x7f42e62e27c0 T7)
==11984==The signal is caused by a READ memory access.
==11984==Hint: address points to the zero page.
    #0 0x55920f6803e9 in terrier::execution::vm::BytecodeModule::GetFuncInfoByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /home/pavlo/Documents/Peloton/Github/terrier/src/include/execution/vm/bytecode_module.h:47
    #1 0x55920f6803e9 in bool terrier::execution::vm::Module::GetFunction<long, terrier::execution::exec::ExecutionContext*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, terrier::execution::vm::ExecutionMode, std::function<long (terrier::execution::exec::ExecutionContext*)>*) /home/pavlo/Documents/Peloton/Github/terrier/src/include/execution/vm/module.h:211
    #2 0x55920f6803e9 in terrier::execution::ExecutableQuery::Run(terrier::common::ManagedPointer<terrier::execution::exec::ExecutionContext>, terrier::execution::vm::ExecutionMode) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/executable_query.cpp:95
    #3 0x55920f5849c4 in terrier::trafficcop::TrafficCop::CodegenAndRunPhysicalPlan(terrier::common::ManagedPointer<terrier::network::ConnectionContext>, terrier::common::ManagedPointer<terrier::network::PostgresPacketWriter>, terrier::common::ManagedPointer<terrier::planner::AbstractPlanNode>, terrier::network::QueryType) const /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop.cpp:338
    #4 0x55920f58dc01 in terrier::trafficcop::TrafficCop::ExecuteStatement(terrier::common::ManagedPointer<terrier::network::ConnectionContext>, terrier::common::ManagedPointer<terrier::network::PostgresPacketWriter>, terrier::common::ManagedPointer<terrier::parser::ParseResult>, terrier::network::QueryType) const /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop.cpp:302
    #5 0x55920f23eda3 in terrier::network::SimpleQueryCommand::Exec(terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter>, terrier::common::ManagedPointer<terrier::network::PostgresPacketWriter>, terrier::common::ManagedPointer<terrier::trafficcop::TrafficCop>, terrier::common::ManagedPointer<terrier::network::ConnectionContext>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_network_commands.cpp:68
    #6 0x55920f24e55f in terrier::network::PostgresProtocolInterpreter::Process(terrier::common::ManagedPointer<terrier::network::ReadBuffer>, terrier::common::ManagedPointer<terrier::network::WriteQueue>, terrier::common::ManagedPointer<terrier::trafficcop::TrafficCop>, terrier::common::ManagedPointer<terrier::network::ConnectionContext>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_protocol_interpreter.cpp:37
    #7 0x55920fbf8bc0 in terrier::network::ConnectionHandle::Process() /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:121
    #8 0x55920fbf8bc0 in operator() /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:105
    #9 0x55920fbf8bc0 in _FUN /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:105
    #10 0x55920fbfc456 in terrier::network::ConnectionHandle::StateMachine::Accept(terrier::network::Transition, terrier::common::ManagedPointer<terrier::network::ConnectionHandle>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:155
    #11 0x55920fbfc935 in terrier::network::ConnectionHandle::HandleEvent(int, short) /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:97
    #12 0x55920fbfc935 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
    #13 0x55920fbfc935 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
    #14 0x7f436e4a08f7  (/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1e8f7)
    #15 0x7f436e4a133e in event_base_loop (/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1f33e)
    #16 0x55920f76fd10 in terrier::EventUtil::EventBaseDispatch(event_base*) /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/event_util.h:92
    #17 0x55920f76fd10 in terrier::common::NotifiableTask::EventLoop() /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:159
    #18 0x55920f76fd10 in terrier::common::NotifiableTask::RunTask() /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:166
    #19 0x55920f76fd10 in terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}::operator()() const /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/dedicated_thread_registry.h:82
    #20 0x55920f76fd10 in void std::__invoke_impl<void, terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(std::__invoke_other, terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) /usr/include/c++/9/bits/invoke.h:60
    #21 0x55920f76fd10 in std::__invoke_result<terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>::type std::__invoke<terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) /usr/include/c++/9/bits/invoke.h:95
    #22 0x55920f76fd10 in void std::thread::_Invoker<std::tuple<terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/9/thread:244
    #23 0x55920f76fd10 in std::thread::_Invoker<std::tuple<terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::operator()() /usr/include/c++/9/thread:251
    #24 0x55920f76fd10 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> > >::_M_run() /usr/include/c++/9/thread:195
    #25 0x7f436e0d0f73  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6f73)
    #26 0x7f436e6dc668 in start_thread /build/glibc-t7JzpG/glibc-2.30/nptl/pthread_create.c:479
    #27 0x7f436ddc2322 in clone (/lib/x86_64-linux-gnu/libc.so.6+0x122322)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/pavlo/Documents/Peloton/Github/terrier/src/include/execution/vm/bytecode_module.h:47 in terrier::execution::vm::BytecodeModule::GetFuncInfoByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
Thread T7 created by T6 here:
    #0 0x7f436e730805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
    #1 0x7f436e0d1238 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd7238)

Thread T6 created by T0 here:
    #0 0x7f436e730805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
    #1 0x7f436e0d1238 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xd7238)
    #2 0x55920f25299b in terrier::network::TerrierServer::RunServer() /home/pavlo/Documents/Peloton/Github/terrier/src/network/terrier_server.cpp:75
    #3 0x60b0000002ff  (<unknown module>)

==11984==ABORTING
```

**Comment by jkosh44** [comment]
This is pending #1135, once that is complete we can rewrite `a || b` as `CONCAT(a, b)` in the binder.
