### ISSUE TITLE
ASAN Error on Nested Query with Aggregation

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#806]
If you execute a nested query that includes an aggregation inside of it, we make it past the optimizer but the execution engine chokes on it with an ASAN error.

Failed query plan is available [here](https://github.com/cmu-db/terrier/files/4284680/plan-json.txt).

## Client

First we can setup the table:
```
terrier=# CREATE TABLE xxx (id INT PRIMARY KEY, val BIGINT);
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1,1),(2,2),(3,3),(4,4),(5,5);
INSERT 0 5
```
Then we can execute a simple nested query:
```
terrier=# SELECT * FROM (SELECT * FROM xxx LIMIT 1) AS x;
 val | id 
-----+----
   1 |  1
(1 row)
```
But if the nested query includes an aggregation we die:
```
terrier=# SELECT * FROM (SELECT COUNT(*) FROM xxx) AS x;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

## Server
```
ASAN:DEADLYSIGNAL
=================================================================
==15671==ERROR: AddressSanitizer: FPE on unknown address 0x5652639747ee (pc 0x5652639747ee bp 0x7f76503a4470 sp 0x7f76503a4170 T7)
    #0 0x5652639747ed in llvm::alignTo(unsigned long, unsigned long, unsigned long) /usr/include/llvm-8/llvm/Support/MathExtras.h:688
    #1 0x5652639747ed in terrier::common::MathUtil::AlignTo(unsigned long, unsigned long) /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/math_util.h:107
    #2 0x5652639747ed in terrier::execution::vm::FunctionInfo::NewLocal(terrier::execution::ast::Type*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, terrier::execution::vm::LocalInfo::Kind) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_function_info.cpp:39
    #3 0x5652639753c6 in terrier::execution::vm::FunctionInfo::NewLocal(terrier::execution::ast::Type*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_function_info.cpp:63
    #4 0x56526399b58f in terrier::execution::vm::BytecodeGenerator::VisitVariableDecl(terrier::execution::ast::VariableDecl*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:345
    #5 0x56526397b40e in terrier::execution::vm::BytecodeGenerator::VisitBlockStmt(terrier::execution::ast::BlockStmt*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:322
    #6 0x56526399addb in terrier::execution::vm::BytecodeGenerator::VisitIterationStatement(terrier::execution::ast::IterationStmt*, terrier::execution::vm::LoopBuilder*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:133
    #7 0x56526399addb in terrier::execution::vm::BytecodeGenerator::VisitForStmt(terrier::execution::ast::ForStmt*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:151
    #8 0x56526397b40e in terrier::execution::vm::BytecodeGenerator::VisitBlockStmt(terrier::execution::ast::BlockStmt*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:322
    #9 0x56526399addb in terrier::execution::vm::BytecodeGenerator::VisitIterationStatement(terrier::execution::ast::IterationStmt*, terrier::execution::vm::LoopBuilder*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:133
    #10 0x56526399addb in terrier::execution::vm::BytecodeGenerator::VisitForStmt(terrier::execution::ast::ForStmt*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:151
    #11 0x56526397b40e in terrier::execution::vm::BytecodeGenerator::VisitBlockStmt(terrier::execution::ast::BlockStmt*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:322
    #12 0x56526397ad6f in terrier::execution::vm::BytecodeGenerator::VisitFunctionDecl(terrier::execution::ast::FunctionDecl*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:179
    #13 0x56526397b6de in terrier::execution::vm::BytecodeGenerator::VisitFile(terrier::execution::ast::File*) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:2358
    #14 0x56526399c1ee in terrier::execution::vm::BytecodeGenerator::Compile(terrier::execution::ast::AstNode*, terrier::execution::exec::ExecutionContext*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/vm/bytecode_generator.cpp:2931
    #15 0x56526391be6c in terrier::execution::ExecutableQuery::ExecutableQuery(terrier::common::ManagedPointer<terrier::planner::AbstractPlanNode>, terrier::common::ManagedPointer<terrier::execution::exec::ExecutionContext>) /home/pavlo/Documents/Peloton/Github/terrier/src/execution/executable_query.cpp:35
    #16 0x56526383690c in terrier::trafficcop::TrafficCop::CodegenAndRunPhysicalPlan(terrier::common::ManagedPointer<terrier::network::ConnectionContext>, terrier::common::ManagedPointer<terrier::network::PostgresPacketWriter>, terrier::common::ManagedPointer<terrier::planner::AbstractPlanNode>, terrier::network::QueryType) const /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop.cpp:335
    #17 0x565263839984 in terrier::trafficcop::TrafficCop::ExecuteStatement(terrier::common::ManagedPointer<terrier::network::ConnectionContext>, terrier::common::ManagedPointer<terrier::network::PostgresPacketWriter>, terrier::common::ManagedPointer<terrier::parser::ParseResult>, terrier::network::QueryType) const /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop.cpp:304
    #18 0x5652635620c9 in terrier::network::SimpleQueryCommand::Exec(terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter>, terrier::common::ManagedPointer<terrier::network::PostgresPacketWriter>, terrier::common::ManagedPointer<terrier::trafficcop::TrafficCop>, terrier::common::ManagedPointer<terrier::network::ConnectionContext>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_network_commands.cpp:68
    #19 0x56526356f37a in terrier::network::PostgresProtocolInterpreter::Process(terrier::common::ManagedPointer<terrier::network::ReadBuffer>, terrier::common::ManagedPointer<terrier::network::WriteQueue>, terrier::common::ManagedPointer<terrier::trafficcop::TrafficCop>, terrier::common::ManagedPointer<terrier::network::ConnectionContext>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_protocol_interpreter.cpp:38
    #20 0x565263ec0bb2 in terrier::network::ConnectionHandle::Process() /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:122
    #21 0x565263ec0bb2 in operator() /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:105
    #22 0x565263ec0bb2 in _FUN /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:105
    #23 0x565263ec32d8 in terrier::network::ConnectionHandle::StateMachine::Accept(terrier::network::Transition, terrier::common::ManagedPointer<terrier::network::ConnectionHandle>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:155
    #24 0x565263ec4454 in terrier::network::ConnectionHandle::HandleEvent(int, short) /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:97
    #25 0x565263ec4454 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
    #26 0x565263ec4454 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
    #27 0x7f76d911d8f7  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1e8f7)
    #28 0x7f76d911e33e in event_base_loop (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1f33e)
    #29 0x565263a1c636 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> > >::_M_run() (/home/pavlo/Documents/Peloton/Github/terrier/build/relwithdebinfo/terrier+0xbfd636)
    #30 0x7f76d83a966e  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd66e)
    #31 0x7f76d93576da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #32 0x7f76d7a6688e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12188e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: FPE /usr/include/llvm-8/llvm/Support/MathExtras.h:688 in llvm::alignTo(unsigned long, unsigned long, unsigned long)
Thread T7 created by T6 here:
    #0 0x7f76d95a6d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7f76d83a9924 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd924)

Thread T6 created by T0 here:
    #0 0x7f76d95a6d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7f76d83a9924 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd924)
    #2 0x565263537370 in terrier::DBMain::Run() /home/pavlo/Documents/Peloton/Github/terrier/src/main/db_main.cpp:14

==15671==ABORTING
```

**Comment by wgy8283335** [comment]
@apavlo I‘d like to take care of this issue.

**Comment by lmwnshn** [comment]
2020-10-19: we don't die, but we don't return results.
