### ISSUE TITLE
Infinite Loop When Updating an Attribute to NULL

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#807]
If you try to set a tuple's attribute to NULL, we appear to get stuck in an infinite loop in the server. The cpu spikes to 100%.

## Client
```
terrier=# CREATE TABLE xxx (id INT PRIMARY KEY, val BIGINT);
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1,1),(2,2);
INSERT 0 2
terrier=# UPDATE xxx SET val = NULL WHERE val = 2;
<HANG>
```

## Server
Every thread but one are either sitting on `epoll_wait` (network) or the other parts of the system (GC, logging). The one execution thread seems to be spinning here:
```
(gdb) thread apply all bt
<SNIP>
Thread 8 (Thread 0x7fff6dca9700 (LWP 16140)):
#0  0x00007ffff6e4d600 in __asan_stack_malloc_4 () from /usr/lib/x86_64-linux-gnu/libasan.so.4
#1  0x00005555564f9cb1 in terrier::execution::compiler::CodeGen::PeekValue (this=0x7fff6dca5c90, transient_val=...) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/codegen.cpp:381
#2  0x00005555566cde20 in terrier::execution::compiler::ConstantTranslator::DeriveExpr (this=0x603000087610, evaluator=<optimized out>) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/expression/constant_translator.cpp:14
#3  0x0000555556725e0b in terrier::execution::compiler::UpdateTranslator::FillPRFromChild (this=this@entry=0x61100003e0c0, builder=builder@entry=0x7fff6dca4230) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/update_translator.cpp:118
#4  0x000055555672651b in terrier::execution::compiler::UpdateTranslator::Consume (this=0x61100003e0c0, builder=0x7fff6dca4230) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/update_translator.cpp:40
#5  0x0000555556713a58 in terrier::execution::compiler::SeqScanTranslator::DoTableScan (this=this@entry=0x610000010340, builder=builder@entry=0x7fff6dca4230) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/seq_scan_translator.cpp:70
#6  0x0000555556713bcb in terrier::execution::compiler::SeqScanTranslator::Produce (this=0x610000010340, builder=0x7fff6dca4230) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/seq_scan_translator.cpp:38
#7  0x0000555556721176 in terrier::execution::compiler::UpdateTranslator::Produce (this=0x61100003e0c0, builder=0x7fff6dca4230) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/update_translator.cpp:23
#8  0x000055555650b41e in terrier::execution::compiler::OutputTranslator::Produce (this=0x60600001b3e0, builder=0x7fff6dca4230) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/output_translator.cpp:25
#9  0x000055555650eba1 in terrier::execution::compiler::Pipeline::Produce (this=0x604000027bd0, query_id=..., pipeline_idx=...) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/pipeline.cpp:50
#10 0x0000555556503828 in terrier::execution::compiler::Compiler::Compile (this=this@entry=0x7fff6dca5c30) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/compiler.cpp:69
#11 0x0000555556050730 in terrier::execution::ExecutableQuery::ExecutableQuery (this=0x7fff6dca7230, physical_plan=..., exec_ctx=...) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/executable_query.cpp:26
#12 0x0000555555f6b90d in terrier::trafficcop::TrafficCop::CodegenAndRunPhysicalPlan (this=this@entry=0x60400001f810, connection_ctx=..., out=..., physical_plan=..., query_type=query_type@entry=terrier::network::QueryType::QUERY_UPDATE)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop.cpp:335
#13 0x0000555555f6e985 in terrier::trafficcop::TrafficCop::ExecuteStatement (this=this@entry=0x60400001f810, connection_ctx=..., out=..., parse_result=..., query_type=<optimized out>) at /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop.cpp:304
#14 0x0000555555c970ca in terrier::network::SimpleQueryCommand::Exec (this=<optimized out>, interpreter=..., out=..., t_cop=..., connection=...) at /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_network_commands.cpp:68
#15 0x0000555555ca437b in terrier::network::PostgresProtocolInterpreter::Process (this=0x606000016460, in=..., out=..., t_cop=..., context=...) at /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_protocol_interpreter.cpp:38
#16 0x00005555565f5bb3 in terrier::network::ConnectionHandle::Process (this=<optimized out>) at /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:122
#17 terrier::network::ConnectionHandle::StateMachine::<lambda(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>)>::operator() (__closure=0x0, w=...) at /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:105
#18 terrier::network::ConnectionHandle::StateMachine::<lambda(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>)>::_FUN(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>) ()
    at /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:105
#19 0x00005555565f82d9 in terrier::network::ConnectionHandle::StateMachine::Accept (this=this@entry=0x611000039ff0, action=<optimized out>, connection=..., connection@entry=...) at /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:155
#20 0x00005555565f9455 in terrier::network::ConnectionHandle::HandleEvent (flags=<optimized out>, fd=<optimized out>, this=0x611000039fd0) at /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:97
#21 terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const (arg=0x611000039fd0, flags=<optimized out>, fd=132, __closure=0x0)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
#22 terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) () at /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
#23 0x00007ffff69c88f8 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#24 0x00007ffff69c933f in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#25 0x0000555556151637 in terrier::EventUtil::EventBaseDispatch (base=<optimized out>) at /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/event_util.h:92
#26 terrier::common::NotifiableTask::EventLoop (this=<optimized out>) at /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:159
#27 terrier::common::NotifiableTask::RunTask (this=<optimized out>) at /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:166
#28 terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}::operator()() const (__closure=0x603000046158)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/dedicated_thread_registry.h:82
#29 std::__invoke_impl<void, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(std::__invoke_other, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#30 std::__invoke<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&)
    (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#31 std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x603000046158) at /usr/include/c++/7/thread:234
#32 std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::operator()() (this=0x603000046158) at /usr/include/c++/7/thread:243
#33 std::thread::_State_impl<std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> > >::_M_run() (this=0x603000046150) at /usr/include/c++/7/thread:186
#34 0x00007ffff5c5466f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#35 0x00007ffff6c026db in start_thread (arg=0x7fff6dca9700) at pthread_create.c:463
#36 0x00007ffff531188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by mbutrovich** [comment]
Can't reproduce this locally anymore.
```
terrier=# CREATE TABLE xxx (id INT PRIMARY KEY, val BIGINT);
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1,1),(2,2);
INSERT 0 2
terrier=# UPDATE xxx SET val = NULL WHERE val = 2;
UPDATE 1
terrier=# SELECT * FROM xxx;
 id | val 
----+-----
  1 |   1
  2 |    
(2 rows)

terrier=# 
```
I'm guessing #831 fixed it.
