### ISSUE TITLE
CompilerTest.SimpleSortTest is Failing

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#811]
You have to compile in debug mode:

```
cmake -DCMAKE_BUILD_TYPE=debug -DTERRIER_BUILD_BENCHMARKS=OFF -DTERRIER_BUILD_TESTS=ON -DTERRIER_USE_ASAN=yes ..
```

```
compiler_test: /home/pavlo/Documents/Peloton/Github/terrier/src/include/planner/plannodes/order_by_plan_node.h:152: size_t terrier::planner::OrderByPlanNode::GetOffset() const: Assertion `(HasLimit()) && ("OrderBy plan has no limit")' failed.
```

Back Trace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5230801 in __GI_abort () at abort.c:79
#2  0x00007ffff522039a in __assert_fail_base (fmt=0x7ffff53a77d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x55555857b6a0 "(HasLimit()) && (\"OrderBy plan has no limit\")", 
    file=file@entry=0x55555857b620 "/home/pavlo/Documents/Peloton/Github/terrier/src/include/planner/plannodes/order_by_plan_node.h", line=line@entry=152, 
    function=function@entry=0x55555857c320 <terrier::planner::OrderByPlanNode::GetOffset() const::__PRETTY_FUNCTION__> "size_t terrier::planner::OrderByPlanNode::GetOffset() const")
    at assert.c:92
#3  0x00007ffff5220412 in __GI___assert_fail (assertion=0x55555857b6a0 "(HasLimit()) && (\"OrderBy plan has no limit\")", 
    file=0x55555857b620 "/home/pavlo/Documents/Peloton/Github/terrier/src/include/planner/plannodes/order_by_plan_node.h", line=152, 
    function=0x55555857c320 <terrier::planner::OrderByPlanNode::GetOffset() const::__PRETTY_FUNCTION__> "size_t terrier::planner::OrderByPlanNode::GetOffset() const") at assert.c:101
#4  0x0000555556d8612e in terrier::planner::OrderByPlanNode::GetOffset (this=0x6080001b25a0)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/include/planner/plannodes/order_by_plan_node.h:152
#5  0x0000555556d8554a in terrier::execution::compiler::SortTopTranslator::GenForLoop (this=0x60700019f630, builder=0x7fffffffb2b0)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/sort_translator.cpp:226
#6  0x0000555556d84ec1 in terrier::execution::compiler::SortTopTranslator::Consume (this=0x60700019f630, builder=0x7fffffffb2b0)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/sort_translator.cpp:201
#7  0x0000555556d84dda in terrier::execution::compiler::SortTopTranslator::Produce (this=0x60700019f630, builder=0x7fffffffb2b0)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/sort_translator.cpp:190
#8  0x0000555556a8f8eb in terrier::execution::compiler::OutputTranslator::Produce (this=0x6060000436a0, builder=0x7fffffffb2b0)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/operator/output_translator.cpp:25
#9  0x0000555556a923bb in terrier::execution::compiler::Pipeline::Produce (this=0x6040003f1390, query_id=..., pipeline_idx=...)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/pipeline.cpp:50
#10 0x0000555556a7e7a7 in terrier::execution::compiler::Compiler::Compile (this=0x7fffffffbb20) at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/compiler/compiler.cpp:69
#11 0x00005555563b61f3 in terrier::execution::ExecutableQuery::ExecutableQuery (this=0x7fffffffdb10, physical_plan=..., exec_ctx=...)
    at /home/pavlo/Documents/Peloton/Github/terrier/src/execution/executable_query.cpp:26
#12 0x00005555560b6ef3 in terrier::execution::compiler::test::CompilerTest_SimpleSortTest_Test::TestBody (this=0x6070001b09d0)
    at /home/pavlo/Documents/Peloton/Github/terrier/test/execution/compiler_test.cpp:1656
#13 0x0000555556e9854d in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x6070001b09d0, method=&virtual testing::Test::TestBody(), 
    location=0x555558603873 "the test body") at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2402
#14 0x0000555556e92e8d in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x6070001b09d0, method=&virtual testing::Test::TestBody(), 
    location=0x555558603873 "the test body") at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2438
#15 0x0000555556e77500 in testing::Test::Run (this=0x6070001b09d0)
    at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2474
#16 0x0000555556e77e3a in testing::TestInfo::Run (this=0x6120000019c0)
    at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2656
#17 0x0000555556e784d7 in testing::TestCase::Run (this=0x611000000040)
    at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2774
#18 0x0000555556e7f480 in testing::internal::UnitTestImpl::RunAllTests (this=0x615000000080)
    at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:4649
#19 0x0000555556e996f5 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x615000000080, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x555556e7f1ae <testing::internal::UnitTestImpl::RunAllTests()>, 
    location=0x5555586040b0 "auxiliary test code (environments or event listeners)")
    at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2402
#20 0x0000555556e93c4d in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x615000000080, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x555556e7f1ae <testing::internal::UnitTestImpl::RunAllTests()>, 
    location=0x5555586040b0 "auxiliary test code (environments or event listeners)")
    at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2438
#21 0x0000555556e7e011 in testing::UnitTest::Run (this=0x555559673940 <testing::UnitTest::GetInstance()::instance>)
    at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:4257
#22 0x0000555556137bee in RUN_ALL_TESTS () at /home/pavlo/Documents/Peloton/Github/terrier/build/googletest_ep-prefix/src/googletest_ep/include/gtest/gtest.h:2233
#23 0x000055555610c6ab in main (argc=1, argv=0x7fffffffe058) at /home/pavlo/Documents/Peloton/Github/terrier/test/execution/compiler_test.cpp:3420
```

**Comment by mbutrovich** [comment]
According to @amlatyrngom it's just an out of date assertion in the plan node that can now be removed.
