### ISSUE TITLE
Loading Smallbank Database with Multiple Threads Fails on OSX

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#877]
If you run the smallbank benchmark with OLTP-Bench on OSX and load the database with multiple threads, then the connection gets messed up and it hangs.

To reproduce, execute our OLTP-Bench script from your local directory (this requires this [commit](https://github.com/cmu-db/terrier/pull/876/commits/eca7797d09775008ec4cf1cc3096ea9f116353fd) that adds support for `--loader-threads` option):
```bash
python3 ../script/testing/oltpbench/run_oltpbench.py \
   smallbank 15,15,15,25,15,15 \
   --build-type=release \
   --loader-threads=2
```

You can see an example output of it working with one loader thread [here](http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-876/3/pipeline/#step-39-log-150) and it failing with two loader threads [here](http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-876/3/pipeline/#step-42-log-190).

```
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO ACCOUNTS VALUES (800000, '0000000000000000000000000000000000000000000000000000000000800000') was aborted: An I/O error occurred while sending to the backend.  Call getNextException to see other errors in the batch.
at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:153)
at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:513)
at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:850)
at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:873)
at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1562)
at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.loadTables(SmallBankLoader.java:129)
at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:114)
at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:63)
at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:514)
... 10 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
at org.postgresql.core.PGStream.flush(PGStream.java:554)
at org.postgresql.core.v3.QueryExecutorImpl.sendSimpleQuery(QueryExecutorImpl.java:1901)
at org.postgresql.core.v3.QueryExecutorImpl.sendOneQuery(QueryExecutorImpl.java:1784)
at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1386)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:494)
... 10 more
```

**Comment by apavlo** [comment]
Smallbank fails on Linux when running with ASAN + debug:

http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-876/6/pipeline#step-41-log-192

**Comment by mbutrovich** [comment]
If I remember correctly, I saw this in Simple and Extended Query mode so I believe it's an issue at the network layer.

**Comment by apavlo** [comment]
This hasn't been an issue for a while. We load the tables with multiple threads on OSX + ASAN.
